# Placeholder settings for ThreatDigest
feeds:
  - https://www.cisa.gov/uscert/ncas/alerts.xml
  - https://www.cisa.gov/uscert/ncas/current-activity.xml
  - https://www.bleepingcomputer.com/feed/
  - https://thehackernews.com/feeds/posts/default
  - https://krebsonsecurity.com/feed/
  - https://msrc.microsoft.com/blog/feed/
  - https://blog.google/threat-analysis-group/rss/
